### ISSUE TITLE
please update dependencies - core-js

### ISSUE THREAD

**Issue by Janine65** [schoero/SwissQRBill#209]
core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

**Comment by schoero** [comment]
I have updated all possible dependencies. But `core-js` is not a direct dependency of `swissqrbill` as `npm ls core-js` shows. 

```
swissqrbill@2.2.0 /Users/Roger/GitHub/SwissQRBill
└─┬ pdfkit@0.11.0
  └─┬ fontkit@1.8.1
    └─┬ babel-runtime@6.26.0
      └── core-js@2.6.12
```

`core-js` is used in `babel-runtime` which is deprecated and used by `fontkit`.  There is actually an [open issue](https://github.com/foliojs/fontkit/issues/219) in fontkit that targets this problem.

So until the problem in fontkit gets solved, I guess we have to live with this warning.

**Comment by Janine65** [comment]
Thanks for Inforation
