### ISSUE TITLE
Fonts License

### ISSUE THREAD

**Issue by Ale-RJP** [schoero/SwissQRBill#308]
The fonts used on the PDFKit library are free for commercial use?

The thing is, the style guide specifications manual for the QR-bill says that the sans-serif fonts permitted are:

- Arial
- Frutiger
- Helvetica
- Liberation Sans

And by default the library uses Helvetica but also gives you the option to use Times and Courier.
Sorry if this is unrelated to an actual issue, just want it to make sure where are this fonts coming from and if we would need to replace them.

**Comment by schoero** [comment]
I don't know for sure. 
I think the fonts come from the [Core 14 AFM Files](https://github.com/foliojs/pdfkit/tree/master/lib/font/data), whose [readme](https://github.com/foliojs/pdfkit/blob/master/lib/font/data/MustRead.html) states that they can be used for any purpose.
There  also was an [issue](https://github.com/foliojs/pdfkit/issues/662) in PDFKit discussing something about font licensing, which also implies that the fonts are free for commercial use. But this is something the developers of PDFKit would have to answer.

**Comment by Ale-RJP** [comment]
Thanks for the quick answare, I'll take a closer look
