### ISSUE TITLE
Add an option to change the page format for QR slip when a second page is needed

### ISSUE THREAD

**Issue by popod** [schoero/SwissQRBill#337]
> When we call the addQRBill() method, SwissQRBill will automatically add the QR slip to the bottom of the current page if there is enough space left, otherwise it will generate a new page in the size of A6/5.

It will be useful to add a parameter to `addQRBill()` to define the new generate page format with A4 for example.

**Comment by schoero** [comment]
v2.4.0 Adds an optional size parameter to `addQRBill()`.

**Comment by popod** [comment]
Very nice ! Thank you :)
