### ISSUE TITLE
SyntaxError: Unexpected token '.' return ibanArray?.join(" ") ?? iban;

### ISSUE THREAD

**Issue by KylianBoss** [schoero/SwissQRBill#346]
Hi,

I've just read the documentation and download your module in my project (**thanks for the job !**)
But when I try to run the code just after adding your module and integrate to my code I've somes errors.

```
.../node_modules/swissqrbill/lib/node/esm/shared/utils.js:26
    return ibanArray?.join(" ") ?? iban;
                     ^

SyntaxError: Unexpected token '.'
```
I tried to correct that but I get other errors after and I don't want to break your code.
Are you aware of this kind of problem in your version 3 ?

I've no error in my code before, I'm using Node js version 12.18.4 in ESM

Thanks for your help.

**Comment by schoero** [comment]
Hi

The issue is that Node.js v12 does not support the optional chaining feature, which throws the error.
Upgrading to Node.js v14 would solve the issue for you. But to solve it for everyone else, I am currently testing if I can transpile the ES versions down to ES6. I will get back to you soon.

**Comment by schoero** [comment]
SwissQRBill v3.0.1 which fixes this issue is now released on npm.
