### ISSUE TITLE
Decimal operator for Germany, France and Swiss market

### ISSUE THREAD

**Issue by ashish20790** [schoero/SwissQRBill#370]
In Germany, France and Swiss market we use "," as a decimal seperator. So when we update the language code to either DE, FR or IT then the decimal separator in amount values should be replaced with "," but it still shows decimal seperator as ".". 
And since Amount is expecting numeric values so we can't pass "," as a decimal seperator.

**Comment by schoero** [comment]
Unfortunately [the specifications (page 17 section 3.5.3)](https://www.paymentstandards.ch/dam/downloads/ig-qr-bill-en.pdf) and the [style guide (page 9 Amount section)](https://www.paymentstandards.ch/dam/downloads/style-guide-en.pdf) do not allow a "," as a decimal separator.

In addition to that, if the data type would be changed to string, we would have to additionally check if the string only contains numbers or a "," and then parse it to be able to encode it in the QR-Code, which would make it unnecessary complex.

**Comment by schoero** [comment]
Unfortunately [the specifications (page 17 section 3.5.3)](https://www.paymentstandards.ch/dam/downloads/ig-qr-bill-en.pdf) and the [style guide (page 9 Amount section)](https://www.paymentstandards.ch/dam/downloads/style-guide-en.pdf) do not allow a "," as a decimal separator.

In addition to that, if the data type would be changed to string, we would have to additionally check if the string only contains numbers or a "," and then parse it to be able to encode it in the QR-Code, which would make it unnecessary complex.

**Comment by schoero** [comment]
Closing as this would violate the specifications.

**Comment by ashish20790** [comment]
Hello @schoero ,

Thanks for your update, i forgot to reply you in time.
