### ISSUE TITLE
reduced QR code height

### ISSUE THREAD

**Issue by clementnuss** [schoero/SwissQRBill#372]
Hi,

could there be a possibility to add an option to e.g. the SVG command, so that the lower part of the generated swissQR code could be removed?
![complete-qr-bill](https://user-images.githubusercontent.com/2116997/157619452-a5499c65-fa72-4e67-8e7b-de4dd8954ce5.png)

Indeed, it takes up valuable space and often makes invoices happen on two pages where one would otherwise suffice.

Thanks for the great library 👏🏻 
Clément

**Comment by schoero** [comment]
Hi Clément

Thank you for your feedback. I would rather not implement such an option, as the layout of the payment part is [strictly specified](https://www.paymentstandards.ch/dam/downloads/style-guide-en.pdf). Cutting out parts of it would violate the specifications and hurt the recognizability of a QR-Bill.

**Comment by clementnuss** [comment]
Hi Roger,

no problem, I understand your position, I was not aware that the standard was so much precise 😆  not much of a surprise in 🇨🇭 though :)
