### ISSUE TITLE
Twint payment slip ?

### ISSUE THREAD

**Issue by popod** [schoero/SwissQRBill#392]
Is it possible to generate Twint payment slip with this module ?

If yes, how to do that ?

If not, I think that this would be something interesting to provide :)

Thank you

**Comment by schoero** [comment]
Yes it is possible. But you need a payment provider that handles the transaction with twint. One such payment provider that I know of is [raisenow](https://www.raisenow.com/en-ch/products/twint/qr-bill-twint#get-started).

You can register your invoices with the payment provider, which then gives you an alternative payment method that you can include in the `av1` and `av2` fields. You can see in [this issue](https://github.com/schoero/SwissQRBill/issues/356) how that could look like.

**Comment by popod** [comment]
Hi, thank you for your detailed reply !
