### ISSUE TITLE
Create a library for Angular

### ISSUE THREAD

**Issue by andreacasarella** [schoero/SwissQRBill#394]
Dear @schoero,
have you considered to create a library for Angular?

Thanks a lot!

**Comment by schoero** [comment]
Hi @andreacasarella 

I have never worked with Angular before.. so the answer is no, I have not considered it so far.

But if you want to create something on top of SwissQRBill, feel free to do so.

**Comment by schoero** [comment]
Closing as an Angular library is out of scope for this project.
