### ISSUE TITLE
swissqrbill not working with Angular 14

### ISSUE THREAD

**Issue by neemaadhikari** [schoero/SwissQRBill#404]
Hi, I'm using swissqrbill  PDFOptions , SVG following are the import I'm using  import { SVG } from "swissqrbill";
import { PDFOptions } from "swissqrbill/lib/node/cjs/shared/types"; everything was working fine with angular 10 but with angular 14 getting pollyfills  any help will be appreciated stuck in this from long time. Can't share code, Kindly help.

**Comment by schoero** [comment]
Hi, unfortunately I`m not familiar with Angular and Angular 14.

Please create a minimal repro on [stackblitz](https://stackblitz.com/fork/angular) that reproduces your issue.

What is the error message you get?

**Comment by schoero** [comment]
Closing as there is no response from the author.
