### ISSUE TITLE
SourceMapping included in minified Bundle

### ISSUE THREAD

**Issue by Juggern4ut** [schoero/SwissQRBill#406]
If you include the library directly as stated in the README like this:

```<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/swissqrbill/lib/browser/bundle/index.js"></script>``` 

You will also load the whole source mapping since it is included in this file. This blows up the file size immensely and is not really needed in a productive environment. I would suggest that the source mapping is removed from this file and made available in another file. This decreses the file size by more than 4'000 kB (over 80%).

Other than that, this is a great project. Thank you for your work.

**Comment by schoero** [comment]
Thank you for noticing and reporting. I have published a new version without the sourcemaps.
