### ISSUE TITLE
Create pdf without npm

### ISSUE THREAD

**Issue by Anastasia-Gorobets** [schoero/SwissQRBill#410]
Hello. Can you please help me? Is it possible to create bill pdf without install npm (project is too old).
Just need in html call js and then save pdf file. 

I thought can do this with it:

`<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/swissqrbill/lib/browser/bundle/index.js"></script>
`

but  not sure how do this without 'import' commands

**Comment by schoero** [comment]
If you include the library using the script tag, like you have mentioned, it will inject the module as `SwissQRBill` to the global scope.

You can access the library by just calling `SwissQRBill.PDF(...)` for example.

Here is a minimal demo to get you started: https://stackblitz.com/edit/web-platform-m2zvga?file=index.html
