### ISSUE TITLE
How can I right-align text in a table?

### ISSUE THREAD

**Issue by felixmerz00** [schoero/SwissQRBill#413]
Hello,

Thank you very much for creating SwissQRBill. I love this package. I have a question tough. I can't figure out how to right-align the text in a specific column of a table. I would like to right-align all values in the column "Price". I use TypeScript. This is the first row in my table.
```
{
  fillColor: '#ECF0F1',
  columns: [
    {
      text: 'Product',
      width: mm2pt(15),
    },
    {
      text: 'Price',
    },
  ],
};
```
I tried using the attribute `align: 'right'`. But this has no effect. Defining the absolute position based on the page width didn't work either. How can I right-align text in specific columns in my table?

Kind regards,
Felix

**Comment by schoero** [comment]
I'm going to close this issue, as the question seems to be answered.
