### ISSUE TITLE
Add the QR slip in an A4 pages

### ISSUE THREAD

**Issue by popod** [schoero/swissqrbill#438]
Hi,

When generating the complete qr bill with a long table, the QR slip is added to a new page. But the new page is not in A4 format.. How to add the QR slip in a new A4 page ?

Thank you

**Comment by schoero** [comment]
There is no option to change this, but you can use [`SwissQRBill.isSpaceSufficient`](https://github.com/schoero/swissqrbill/blob/main/docs/pdf/index.md#method-swissqrbillisspacesufficientdoc-xposition-yposition) to calculate if there is sufficient space on the current page and add a page manually if necessary.

```ts
if (!SwissQRBill.isSpaceSufficient(pdf, 0, pdf.y)) {
  pdf.addPage({ size: 'A4' });
}
```
Working example: [stackblitz.com](https://stackblitz.com/fork/schoero-swissqrbill-jf3zlr?file=src%2Fpdf.js&startScript=generate)

**Comment by popod** [comment]
Hi @schoero 

Thank you for your fast reply ! This is perfect :)

I think that adding that to the full bill exemple could be great.
